name: Deploy back
on:
  workflow_dispatch:
jobs:
  Deploy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./back
          tags: test
          push: false
