name: Deploy
on:
  workflow_dispatch:
    inputs:
      deploy-front-or-back:
        required: true
        default: 'Deploy front'
        type: choice
        options:
        - 'Deploy front'
        - 'Deploy back'
jobs:
  Deploy-front:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-front-or-back == 'Deploy front' }}
    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./front
          tags: test
          push: false
